# Introduction - Data Types and Data Structures

In [ ]:
# Strings
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [ ]:
my_New_string1 = 'Goodbye'
my_New_string2 = "World"
print(my_New_string1 + ' ' + my_New_string2)

Goodbye World


In [ ]:
# Integer
my_int = 10
print(my_int)

10


In [ ]:
my_New_int = 1276
print(my_New_int)

1276


In [ ]:
print(type(my_int))
print(type(my_New_int))

<class 'int'>
<class 'int'>


In [ ]:
# String to integer
my_string = "100"
print(type(my_string))

<class 'str'>


In [ ]:
my_int = int(my_string)
print(type(my_int))

<class 'int'>


In [ ]:
my_New_string = "727"
print(type(my_New_string))

<class 'str'>


In [ ]:
my_New_int = int(my_New_string)
print(type(my_New_int))

<class 'int'>


In [ ]:
# Floating Point Number
my_float = 1.0
my_float_b = 727.27
print(type(my_float))
print(type(my_float_b))

<class 'float'>
<class 'float'>


In [ ]:
my_int = 1
myint = 727
print(type(my_int))
print(type(myint))

<class 'int'>
<class 'int'>


In [ ]:
# Boolean
my_bool = False
my_bool_b= True
print(my_bool)
print(my_bool_b)

False
True


In [ ]:
print(type(my_bool))
print(type(my_bool_b))

<class 'bool'>
<class 'bool'>


In [ ]:
# Basic Math Operations
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [ ]:
print("Suma ", 700+27)
print("Resta ", 456-98)
print("Multiplicacion ", 5*3)
print("Division", 727/2)
print("Exponente", 3**3)

Suma  727
Resta  358
Multiplicacion  15
Division 363.5
Exponente 27


In [ ]:
#  ----- Data Collections -----
# -- List
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)
my_New_List = ['Goodbye', "World", 727,5,78]
print(my_New_List)

['Quant', 'Connect', 1, 2, 3]
['Goodbye', 'World', 727, 5, 78]


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))

5


In [ ]:
my_New_List = ['Goodbye', "World", 727,5,78, "Cheems " + 'Ansiedad',6]
print(len(my_New_List))
print(my_New_List)

7
['Goodbye', 'World', 727, 5, 78, 'Cheems Ansiedad', 6]


In [ ]:
print(my_list[0])

Quant


In [ ]:
print(my_list[len(my_list) - 1])

3


In [ ]:
print(my_New_List[0])

Goodbye


In [ ]:
print(my_New_List[len(my_New_List) - 1])

6


In [ ]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [ ]:
my_New_List = ['Goodbye', "World", 727,5,78, "Cheems",6]
my_New_List[5] = 'Doge'
print(my_New_List)

['Goodbye', 'World', 727, 5, 78, 'Doge', 6]


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [ ]:
my_New_List = ['Goodbye', "World", 727,5,78, "Cheems",6]
print(my_New_List[2:6])

[727, 5, 78, 'Cheems']


In [ ]:
print(my_list[1:])

['Connect', 1, 2, 3]


In [ ]:
print(my_New_List[3:])

[5, 78, 'Cheems', 6]


In [ ]:
# Add and Remove elements from the list
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']


In [ ]:
my_list.remove('Hello')
print(my_list)

['Quant', 'Hello']


In [ ]:
my_New_List = ['Goodbye', "World", 727,5,78, "Cheems",6]
my_New_List.append('Sayonara')
print(my_New_List)

['Goodbye', 'World', 727, 5, 78, 'Cheems', 6, 'Sayonara']


In [ ]:
my_New_List.remove('Sayonara')
print(my_New_List)

['Goodbye', 'World', 727, 5, 78, 'Cheems', 6]


In [ ]:
my_tuple = ('Welcome','to','QuantConnect')

In [ ]:
my_New_Tuple = ('Goodbye',"to",'World')

In [ ]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [ ]:
my_New_Tuple = ('Goodbye',"to",'World')
print(my_New_Tuple[1:])

('to', 'World')


In [ ]:
# -- Set 
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'IBM', 'GOOG', 'AAPL', 'F', 'FB'}


In [ ]:
stock_New_list = ['ASD','gg','DELL','GG','OSU','XD','F','GLWP','ASD']
stock_New_set = set(stock_New_list)
print(stock_New_set)

{'GG', 'gg', 'OSU', 'XD', 'ASD', 'GLWP', 'F', 'DELL'}


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic['GOOG'])

Alphabet


In [ ]:
my_New_dic = {'CHEEMS': 'Ansiedad', 'TW': 'Twitch', 727: 'Circle','WIN':'Linus'}
print(my_New_dic[727])
print(my_New_dic['TW'])

Circle
Twitch


In [ ]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [ ]:
my_New_dic['CHEEMS'] = 'Doge'
print(my_New_dic['CHEEMS'])

Doge


In [ ]:
print(my_dic.keys())
print(my_New_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])
dict_keys(['CHEEMS', 'TW', 727, 'WIN'])


In [ ]:
#  ----- Common String Operations -----
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [ ]:
print("Counting the number of e's in this sentence".count('e'))

6


In [ ]:
print("Contando el numero de e's en la oración".count('e'))

5


In [ ]:
print('The first time e appears in this sentence'.find('e'))

2


In [ ]:
print('La primerva vez que aparece la e en la oración'.find('e')) 

7


In [ ]:
print('all the a in this sentence now becomes e'.replace('a','e'))

ell the e in this sentence now becomes e


In [ ]:
print('Todas las a en la oración ahora se convierten en e'.replace('a','e'))

Todes les e en le oreción ehore se convierten en e


In [ ]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

2016-04-01 09:43:00


In [ ]:
hour = time.split(':')[0]
print(hour)

09


In [ ]:
new_Time = '15/10/2021 07:27:00'
splited_list = new_Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)

15/10/2021 07:27:00


In [ ]:
hour = time.split(':')[0]
print(hour)

07


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [ ]:
my_New_time = 'Hour: {}, Minute: {}'.format(7, 27)
print(my_New_time)

Hour: 7, Minute: 27


In [ ]:
print('pi is %f' % 3.14)

pi is 3.140000


In [ ]:
print("e is %f" % 2.71)

e is 2.710000


In [ ]:
print('%s to %s' % ('Welcome', 'QuantConnect'))

Welcome to QuantConnect


In [ ]:
print('%s to %s' % ('Goodbye', 'World'))

Goodbye to World


# Logical Operations and Loops

In [ ]:
# -- Logical Operations --
print (1 == 0)    # 1 equals 0
print (1 == 1)    # 1 equals 1
print (1 != 0)    # 1 is not equal to 0
print (5 >= 5)    # 5 is greater than or equal to 5
print (5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [ ]:
print (727 == 272)    # 727 equals 272
print (727 == 727)    # 727 equals 727
print (6 != 7)        # 6 is not equal to 7
print (23 >= 23)      # 23 is greater than or equal to 23
print (23 > 23)      # 23 is greater than 23
print (56 >= 99)      # 56 is greater than or equal to 99

False
True
True
True
False
False


In [ ]:
print (2 > 1 and 3 > 2)
print (2 > 1 and 3 < 2)
print (2 > 1 or  3 < 2)
print (2 < 1 and 3 < 2)

True
False
True
False


In [ ]:
print ('a' == 'a' and 3 > 2)
print (23 > 10 and -3 < 2)
print (2 < 1 or  '3' != 3)
print (12 < 8 and 72 < 7)

True
True
True
False


In [ ]:
print (3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3))
print (3 < 2 or 1 > 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3))

True
False


In [ ]:
print (727 > 700 or -23 < 0) and ('a'!='a' and 4>3) and not ( 5 < -2 or -1 < 3 and (1!=3 and 4>3))
print (34 < 12 or -45 > 6) and (1!=3 and 4>3) and not ( 87 < 4 or -727 < 789 and (my_New_int!=3 and 4>3))

True
False


In [ ]:
i = 0
if i == 0: print ('i == 0 is True')

i == 0 is True


In [ ]:
j = 1
if j == 0: print('j == 0 is True')
else: print('j == 0 is False') 

j == 0 is False


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print ('p and q is true')
elif p and not q:
    print ('q is false')
elif q and not p:
    print ('p is false')
else:
    print ('None of p and q is true')

q is false


In [ ]:
p = "a" == 'a'
q = 2 > 3
if p and q:
    print ('p and q is true')
elif p and not q:
    print ('q is false')
elif q and not p:
    print ('p is false')
else:
    print ('None of p and q is true')

q is false


In [ ]:
# -- While -- 
i = 0
while i < 5:
    print (i)
    i += 1

0
1
2
3
4


In [ ]:
j = 0
while j < 5:
    print ("Goodbye World: " + str(j))
    j += 1

Goodbye World: 0
Goodbye World: 1
Goodbye World: 2
Goodbye World: 3
Goodbye World: 4


In [ ]:
# -- For Loop -- 
for x in [1,2,3,4,5]: print (x)

1
2
3
4
5


In [ ]:
for y in [20,21,22,23,24]: print (y)

20
21
22
23
24


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print (new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [ ]:
stocks = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH']
selected = ['TW','TWITCH']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print (new_list)

['DOGE', 'COIN', 'DELL', 'IT', 'VGA', 'DVI', 'GGWP']


In [ ]:
# -- Breaks and Continue -- 
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [ ]:
stocks = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH']
for stock in stocks:
    print (stock)
    if stock == 'GGWP': break

DOGE
COIN
DELL
IT
TW
VGA
DVI
GGWP


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print (stock)

AAPL
GOOG
IBM
F
V
G
GE


In [ ]:
stocks = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH']
for stock in stocks:
    if stock == 'IT': continue
    print (stock)

DOGE
COIN
DELL
TW
VGA
DVI
GGWP
TWITCH


In [2]:
# -- List Comprehension --
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print (squares)

[1, 4, 9, 16, 25]


In [7]:
cubes = []
for j in [1,2,3,4,5,6]:
    cubes.append(j**3)
print (cubes)

[1, 8, 27, 64, 125, 216]


In [5]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print (squares)

[1, 4, 9, 16, 25]


In [9]:
numbers = [1,2,3,4,5,6,7]
cubes = [x**3 for x in numbers]
print (cubes)

[1, 8, 27, 64, 125, 216, 343]


In [11]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [12]:
stocks = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH']
selected = ['TW','TWITCH']
new_list = [x for x in stocks if x not in selected]
print (new_list)

['DOGE', 'COIN', 'DELL', 'IT', 'VGA', 'DVI', 'GGWP']


In [16]:
print ([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [17]:
print ([(x, y) for x in [1,2,3,7] for y in [3,1,4,6] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['GGWP','DOGE','TW','OSU']
                                for y in ['O','Z','B','CK'] if x != y])

[(1, 3), (1, 4), (1, 6), (2, 3), (2, 1), (2, 4), (2, 6), (3, 1), (3, 4), (3, 6), (7, 3), (7, 1), (7, 4), (7, 6)]
['GGWP vs O', 'GGWP vs Z', 'GGWP vs B', 'GGWP vs CK', 'DOGE vs O', 'DOGE vs Z', 'DOGE vs B', 'DOGE vs CK', 'TW vs O', 'TW vs Z', 'TW vs B', 'TW vs CK', 'OSU vs O', 'OSU vs Z', 'OSU vs B', 'OSU vs CK']


# Functions and Objective-Oriented Programming

In [19]:
# -- Functions --
def product(x,y):
    return x*y
print (product(2,3))
print (product(5,10))

6
50


In [25]:
def divison(x,y):
    return x/y
print (divison(2,3))
print (divison(5,10))

0.6666666666666666
0.5


In [26]:
def say_hi():
    print ("Welcome to QuantConnect")
say_hi()

Welcome to QuantConnect


In [27]:
def say_goodbye():
    print ("Goodbye World")
say_goodbye()

Goodbye World


In [39]:
# Function range()
print ([x for x in range(10)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
print ([x for x in range(15)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [38]:
print ([x for x in range(1,11)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [40]:
print ([x for x in range(1,15)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


In [41]:
print ([x for x in range(1, 11, 2)])

[1, 3, 5, 7, 9]


In [42]:
print ([x for x in range(1, 15, 2)])

[1, 3, 5, 7, 9, 11, 13]


In [44]:
# len() and range()
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print ("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [49]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print ("The number of tickers is {}".format(len(tickers)))
for ticker in tickers:
  print(ticker)

The number of tickers is 8
AAPL
GOOGL
IBM
FB
F
V
G
GE


In [47]:
tickers = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH','WYSI']
print ("El numero de tickers es {}".format(len(tickers)))
for k in range(len(tickers)):
    print (k + 1, tickers[k])

El numero de tickers es 10
1 DOGE
2 COIN
3 DELL
4 IT
5 TW
6 VGA
7 DVI
8 GGWP
9 TWITCH
10 WYSI


In [50]:
tickers = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH','WYSI']
print ("El numero de tickers es {}".format(len(tickers)))
for ticker in tickers:
  print(ticker)

El numero de tickers es 10
DOGE
COIN
DELL
IT
TW
VGA
DVI
GGWP
TWITCH
WYSI


In [51]:
# map()
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [56]:
tickers = ['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH','WYSI']
print(list(map(len,tickers)))

[4, 4, 4, 2, 2, 3, 3, 4, 6, 4]


In [55]:
# lambda and map()
print(list(map(lambda x: x**2, range(10))))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [57]:
print(list(map(lambda x: x**3, range(15))))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744]


In [59]:
print(list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1])))

[6, 6, 6, 6, 6]


In [61]:
print(list(map(lambda x, y: x+y, [1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1])))
print(list(map(lambda x, y: x-y, [1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1])))

[10, 10, 10, 10, 10, 10, 10, 10, 10]
[-8, -6, -4, -2, 0, 2, 4, 6, 8]


In [62]:
# sorted()
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [63]:
sorted(['DOGE','COIN','DELL','IT','TW','VGA', 'DVI', 'GGWP','TWITCH','WYSI'])

['COIN', 'DELL', 'DOGE', 'DVI', 'GGWP', 'IT', 'TW', 'TWITCH', 'VGA', 'WYSI']

In [66]:
# key and sorted
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [67]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[0])

[('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71),
 ('MSFT', 69),
 ('WMT', 75.32)]

In [68]:
price_list = [('DOGE', 144.09), ('COIN', 911.71), ('DELL', 69), ('IT', 150), ('TW', 75.32),('VGA', 7.27),('WISY', 727),('GGWP', 50)]
sorted(price_list, key = lambda x: x[1])

[('VGA', 7.27),
 ('GGWP', 50),
 ('DELL', 69),
 ('TW', 75.32),
 ('DOGE', 144.09),
 ('IT', 150),
 ('WISY', 727),
 ('COIN', 911.71)]

In [69]:
price_list = [('DOGE', 144.09), ('COIN', 911.71), ('DELL', 69), ('IT', 150), ('TW', 75.32),('VGA', 7.27),('WISY', 727),('GGWP', 50)]
sorted(price_list, key = lambda x: x[0])

[('COIN', 911.71),
 ('DELL', 69),
 ('DOGE', 144.09),
 ('GGWP', 50),
 ('IT', 150),
 ('TW', 75.32),
 ('VGA', 7.27),
 ('WISY', 727)]

In [73]:
# Argument reverse
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [75]:
price_list = [('DOGE', 144.09), ('COIN', 911.71), ('DELL', 69), ('IT', 150), ('TW', 75.32),('VGA', 7.27),('WISY', 727),('GGWP', 50)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('COIN', 911.71),
 ('WISY', 727),
 ('IT', 150),
 ('DOGE', 144.09),
 ('TW', 75.32),
 ('DELL', 69),
 ('GGWP', 50),
 ('VGA', 7.27)]

In [71]:
# method .sort()
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [74]:
price_list = [('DOGE', 144.09), ('COIN', 911.71), ('DELL', 69), ('IT', 150), ('TW', 75.32),('VGA', 7.27),('WISY', 727),('GGWP', 50)]
price_list.sort(key = lambda x: x[1])
print (price_list)

[('VGA', 7.27), ('GGWP', 50), ('DELL', 69), ('TW', 75.32), ('DOGE', 144.09), ('IT', 150), ('WISY', 727), ('COIN', 911.71)]


In [77]:
# ------ Object-Oriented Programming -------
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print (self.rate_return)

In [79]:
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)
ibm = Stock('IBM',727,800,345987)

In [84]:
apple.ticker

'AAPL'

In [85]:
ibm.ticker

'IBM'

In [86]:
google.print_return()
ibm.print_return()

0.014465338822744034
0.10041265474552952


In [88]:
google.update(912.8,913.4)
google.print_return()

0.0006573181419806673


In [90]:
ibm.update(727.27,800.78)
ibm.print_return()

0.10107662903735881


In [91]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [93]:
ibm.ceo = 'Arvind Krishna'
ibm.ceo

'Arvind Krishna'

In [92]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [94]:
dir(ibm)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [95]:
# -- Inheritance -- 
class Child(Stock):
    def __init__(self, name):
        self.name = name

In [109]:
aa = Child('AA')
bb = Child('BB')
print (aa.name)
print (bb.name)

AA
BB


In [110]:
aa.update(100, 102)
bb.update(727, 800)
print (aa.open)
print (bb.open)

100
727


In [111]:
print (aa.close)
print (bb.close)

102
800


In [112]:
print (aa.print_return())
print (bb.print_return())

0.020000000000000018
None
0.10041265474552952
None


# NumPy and Basic Pandas

In [115]:
# -- NumPy -- 
import numpy as np
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print (price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [118]:
my_price_list = [727.01, 727.27, 728.68, 725.78, 780.12, 720.42, 717.23]
my_price_array = np.array(my_price_list)
print (my_price_array, type(my_price_array))

[727.01 727.27 728.68 725.78 780.12 720.42 717.23] <class 'numpy.ndarray'>


In [120]:
Ar = np.array([[1,3], [2,4]])
print (Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [122]:
Arr = np.array([[45,23], [72,7]])
print (Arr, type(Arr))

[[45 23]
 [72  7]] <class 'numpy.ndarray'>


In [123]:
print (Ar.shape)
print (Arr.shape)

(2, 2)
(2, 2)


In [124]:
print (Ar[0])

[1 3]


In [125]:
print (Ar[1])

[2 4]


In [126]:
print (Arr[0])

[45 23]


In [127]:
print (Arr[1])

[72  7]


In [128]:
print ('First column:', Ar[:,0])

First column: [1 2]


In [129]:
print ('Primera Columna:', Arr[:,0])

Primera Columna: [45 72]


In [130]:
print ('Second column:', Ar[:,1])

Second column: [3 4]


In [131]:
print ('Segunda Columna:', Arr[:,1])

Segunda Columna: [23  7]


In [133]:
# -- Array Functions --
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [134]:
np.log(my_price_array)

array([6.58894023, 6.5892978 , 6.59123468, 6.58724694, 6.65944775,
       6.57983438, 6.57539657])

In [135]:
np.mean(price_array)

143.89666666666668

In [136]:
np.mean(my_price_array)

732.3585714285715

In [138]:
print (np.std(price_array))

0.9673790478515796


In [139]:
print (np.std(my_price_array))

19.870536284783515


In [140]:
print (np.sum(price_array))

863.38


In [141]:
print (np.sum(my_price_array))

5126.51


In [142]:
print (np.max(price_array))

145.83


In [143]:
print (np.max(my_price_array))

780.12


In [147]:
# ------- Pandas -------
import pandas as pd
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print (s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [148]:
my_price = [727.01, 727.27, 728.68, 725.78, 780.12, 720.42, 717.23]
ss = pd.Series(my_price)
print (ss)

0    727.01
1    727.27
2    728.68
3    725.78
4    780.12
5    720.42
6    717.23
dtype: float64


In [149]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print (s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [152]:
ss = pd.Series(my_price, index = ['a', 'b', 'c', 'd', 'e', 'f','g'])
print (ss)

a    727.01
b    727.27
c    728.68
d    725.78
e    780.12
f    720.42
g    717.23
dtype: float64


In [153]:
s.index = [6,5,4,3,2,1]
print (s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [155]:
ss.index = [16,15,14,13,12,11,10]
print (ss)

16    727.01
15    727.27
14    728.68
13    725.78
12    780.12
11    720.42
10    717.23
dtype: float64


In [156]:
print (s[1:])
print (s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [157]:
print (ss[1:])
print (ss[:-2])

15    727.27
14    728.68
13    725.78
12    780.12
11    720.42
10    717.23
dtype: float64
16    727.01
15    727.27
14    728.68
13    725.78
12    780.12
dtype: float64


In [158]:
print (s[4])
s[4] = 0
print (s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [160]:
print (ss[14])
ss[14] = 0
print (ss)

728.68
16    727.01
15    727.27
14      0.00
13    725.78
12    780.12
11    720.42
10    717.23
dtype: float64


In [161]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [162]:
ss = pd.Series(my_price, name = 'IBM Prices')
print (ss)
print (ss.name)

0    727.01
1    727.27
2    728.68
3    725.78
4    780.12
5    720.42
6    717.23
Name: IBM Prices, dtype: float64
IBM Prices


In [163]:
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [164]:
print (ss.describe())

count      7.000000
mean     732.358571
std       21.462632
min      717.230000
25%      723.100000
50%      727.010000
75%      727.975000
max      780.120000
Name: IBM Prices, dtype: float64


In [183]:
# -- Time Index --
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [185]:
time_index = pd.date_range('2017-01-01', periods = len(ss), freq = 'D')
print (time_index)
ss.index = time_index
print (ss)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06', '2017-01-07'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    727.01
2017-01-02    727.27
2017-01-03    728.68
2017-01-04    725.78
2017-01-05    780.12
2017-01-06    720.42
2017-01-07    717.23
Freq: D, Name: IBM Prices, dtype: float64


In [167]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [172]:
print (s.iloc[1])

145.83


In [173]:
ss.index = [16,15,14,13,12,11,10]
print (ss)
print (ss[11])

16    727.01
15    727.27
14    728.68
13    725.78
12    780.12
11    720.42
10    717.23
Name: IBM Prices, dtype: float64
720.42


In [174]:
print (ss.iloc[1])

727.27


In [184]:
s.index = time_index
print (s['2017-01-03'])

143.68


In [187]:
ss.index = time_index
print (ss['2017-01-02'])

727.27


In [189]:
print (s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [190]:
print (ss['2017-01-02':'2017-01-05'])

2017-01-02    727.27
2017-01-03    728.68
2017-01-04    725.78
2017-01-05    780.12
Freq: D, Name: IBM Prices, dtype: float64


In [191]:
print (s[s < np.mean(s)])
print (s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [192]:
print (ss[ss < np.mean(ss)])
print (ss[(ss > np.mean(ss)) & (ss < np.mean(ss) + 1.64*np.std(ss))])

2017-01-01    727.01
2017-01-02    727.27
2017-01-03    728.68
2017-01-04    725.78
2017-01-06    720.42
2017-01-07    717.23
Name: IBM Prices, dtype: float64
Series([], Freq: D, Name: IBM Prices, dtype: float64)
